[{capture append="oxidBlock_content"}]
    [{agextranetpage route="accountsubscriptioncontract" height="2500px" pageuid=$pageuid}]
[{/capture}]
[{capture append="oxidBlock_sidebar"}]
    [{include file="page/account/inc/account_menu.tpl" active_link="subscription_contracts"}]
[{/capture}]
[{include file="layout/page.tpl" sidebar="Left"}]
