alter table oxarticles add WWFOREIGNID char(36) NOT NULL;
alter table oxarticles add WWFOREIGNPARENTID char(36) NOT NULL;
alter table oxcategories add WWFOREIGNID char(36) NOT NULL;
alter table oxcategories add WWFOREIGNPARENTID char(36) NOT NULL;
alter table oxattribute add WWFOREIGNID char(36) NOT NULL;
alter table oxselectlist add WWFOREIGNID char(36) NOT NULL;
alter table oxmanufacturers add WWFOREIGNID char(36) NOT NULL;
alter table oxvendor add WWFOREIGNID char(36) NOT NULL;
alter table oxorder add WWFOREIGNID char(36) NOT NULL;
alter table oxorderarticles add WWFOREIGNID char(36) NOT NULL;
alter table oxselectlist add OXSORT int(11) NOT NULL;
alter table oxattribute add OXIDENT varchar(64) NOT NULL;
alter table oxorder add WWPENDING tinyint(1) NOT NULL;
alter table oxorder add OXTIMESTAMP timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table oxuser add OXTIMESTAMP timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table oxuser add WWDELETED tinyint(1) NOT NULL;

alter table oxorder add OXGIFTCARDCOST double NOT NULL default '0';
alter table oxorder add OXGIFTCARDVAT double NOT NULL default '0';
alter table oxorder add OXBILLDATE timestamp NOT NULL;
alter table oxorder add OXTSPROTECTCOSTS double NOT NULL default '0';
alter table oxorder add OXISNETTOMODE TINYINT(1) NOT NULL default '0';

CREATE TABLE IF NOT EXISTS `wawitokens` (
  `id` char(32) COLLATE latin1_general_ci NOT NULL,
  `expired` datetime NOT NULL,
  `used` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

ALTER TABLE oxselectlist ADD WWVALICONS TEXT NOT NULL;
ALTER TABLE oxselectlist ADD WWVALDATA TEXT NOT NULL;
ALTER TABLE oxselectlist ADD WWVALDATA_1 TEXT NOT NULL;
ALTER TABLE oxselectlist ADD WWVALDATA_2 TEXT NOT NULL;
ALTER TABLE oxselectlist ADD WWVALDATA_3 TEXT NOT NULL;

ALTER TABLE oxvouchers ADD `AGRESTVALUE` FLOAT(9,2); 
ALTER TABLE oxarticles ADD `AGISVOUCHER` TINYINT(1) NOT NULL; 
ALTER TABLE oxorderarticles ADD `AGISVOUCHER` TINYINT(1) NOT NULL DEFAULT -1; 
ALTER TABLE oxorderarticles ADD `AGVOUCHERSSENT` TINYINT(1) NOT NULL DEFAULT 0; 

ALTER TABLE oxvouchers ADD `AGISVOUCHER` TINYINT(1)  NOT NULL; 

ALTER TABLE oxorder ADD `AGGIFTEDVOUCHERDISCOUNT` FLOAT(9,2); 
ALTER TABLE oxvoucherseries ADD `AGSALEORDERID` CHAR(32);
ALTER TABLE oxvouchers ADD `AGSALEORDERID` CHAR(32);
ALTER TABLE oxvouchers ADD `AGSALEORDERARTICLEID` CHAR(32); 

ALTER TABLE oxvoucherseries ADD WWFOREIGNID char(36) NOT NULL;
ALTER TABLE oxvouchers ADD WWFOREIGNID char(36) NOT NULL;

alter table oxvoucherseries add OXTIMESTAMP timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
alter table oxvouchers add OXTIMESTAMP timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE oxarticles MODIFY `AGISVOUCHER` TINYINT(1) NOT NULL;
ALTER TABLE oxorderarticles MODIFY `AGISVOUCHER` TINYINT(1) NOT NULL DEFAULT -1; 
ALTER TABLE oxorderarticles MODIFY `AGVOUCHERSSENT` TINYINT(1) NOT NULL DEFAULT 0; 

CREATE TABLE IF NOT EXISTS `oxgroup2price` (
  `OXID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXGROUPID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXARTICLEID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXPRICE` DOUBLE NOT NULL
) DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

ALTER TABLE oxgroups add WWFOREIGNID char(36) NOT NULL;
ALTER TABLE oxuser add WWFOREIGNID char(36) NOT NULL;


CREATE TABLE IF NOT EXISTS `oxarticle2group` (
  `OXID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXGROUPSID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXOBJECTID` char(32) COLLATE latin1_general_ci NOT NULL
) DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

ALTER TABLE `oxgroup2price` CHANGE `OXID` `OXID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxgroup2price` CHANGE `OXGROUPID` `OXGROUPID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxgroup2price` CHANGE `OXARTICLEID` `OXARTICLEID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxgroup2price` ADD OXSORT INT(11) NOT NULL;

ALTER TABLE `oxarticle2group` CHANGE `OXID` `OXID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxarticle2group` CHANGE `OXGROUPSID` `OXGROUPSID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxarticle2group` CHANGE `OXOBJECTID` `OXOBJECTID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;

ALTER TABLE `oxprice2article` ADD `OXGROUPSID` CHAR(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;

ALTER TABLE `oxgroup2price` ADD KEY `OXARTICLEID` (`OXARTICLEID`);
ALTER TABLE `oxgroup2price` ADD KEY `OXGROUPID` (`OXGROUPID`) USING BTREE;
ALTER TABLE `oxdiscount` ADD WWFOREIGNID char(36) NOT NULL;
ALTER TABLE `oxarticles` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxarticles` ADD INDEX `WWFOREIGNPARENTID` (`WWFOREIGNPARENTID`);
ALTER TABLE `oxcategories` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxcategories` ADD INDEX `WWFOREIGNPARENTID` (`WWFOREIGNPARENTID`);
ALTER TABLE `oxuser` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxorder` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxorderarticles` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxdiscount` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxvoucherseries` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);
ALTER TABLE `oxvouchers` ADD INDEX `WWFOREIGNID` (`WWFOREIGNID`);

ALTER TABLE `oxarticle2group`
  ADD PRIMARY KEY (`OXID`),
  ADD KEY `OXMAINIDX` (`OXGROUPSID`,`OXOBJECTID`),
  ADD KEY `OXARTID` (`OXOBJECTID`);

ALTER TABLE `oxgroup2price`
  ADD PRIMARY KEY (`OXID`);

ALTER TABLE wawitokens ADD USERID char(36) NOT NULL;

ALTER TABLE oxartextends add OXTAGS char(255) NOT NULL;
ALTER TABLE oxartextends add OXTAGS_1 char(255) NOT NULL;
ALTER TABLE oxartextends add OXTAGS_2 char(255) NOT NULL;
ALTER TABLE oxartextends add OXTAGS_3 char(255) NOT NULL;
ALTER TABLE oxartextends add OXTAGS_4 char(255) NOT NULL;

alter table oxuser add WWUPDATEBASKET tinyint(1) NOT NULL;
alter table oxuser add WWCUSTOMERNUMBER varchar(128) NOT NULL;
alter table oxuser add WWFOREIGNPASSWORD varchar(128) NOT NULL;
alter table oxorder add WWUSERAGENT varchar(255) NOT NULL;
alter table oxorder add WWAGENTPARAMETER text NOT NULL;

ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_2`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_3`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_4`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_5`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_6`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_7`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_8`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_9`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_10`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_11`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_12`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_13`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_14`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_15`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNID_16`;

ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_2`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_3`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_4`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_5`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_6`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_7`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_8`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_9`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_10`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_11`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_12`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_13`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_14`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_15`;
ALTER TABLE `oxarticles` DROP INDEX `WWFOREIGNPARENTID_16`;

ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_2`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_3`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_4`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_5`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_6`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_7`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_8`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_9`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_10`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_11`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_12`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_13`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_14`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_15`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_16`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_17`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_18`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_19`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_20`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_21`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_22`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNID_23`;

ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_2`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_3`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_4`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_5`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_6`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_7`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_8`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_9`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_10`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_11`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_12`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_13`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_14`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_15`;
ALTER TABLE `oxcategories` DROP INDEX `WWFOREIGNPARENTID_16`;

CREATE TABLE IF NOT EXISTS `oxvoucherserieaccessory` ( 
`OXID` CHAR(32) COLLATE latin1_general_ci NOT NULL , 
`OXQUANTITY` FLOAT NOT NULL , 
`OXPRICE` FLOAT NOT NULL , 
`OXARTICLEID` CHAR(32) COLLATE latin1_general_ci NOT NULL , 
`OXVOUCHERSERIEID` CHAR(32) COLLATE latin1_general_ci NOT NULL , 
PRIMARY KEY (`OXID`), INDEX (`OXARTICLEID`), INDEX (`OXVOUCHERSERIEID`));

CREATE TABLE IF NOT EXISTS `oxcategory2group` (
  `OXID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXGROUPSID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXOBJECTID` char(32) COLLATE latin1_general_ci NOT NULL
) DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

ALTER TABLE `oxcategory2group`
  ADD PRIMARY KEY (`OXID`),
  ADD KEY `OXMAINIDX` (`OXGROUPSID`,`OXOBJECTID`),
  ADD KEY `OXARTID` (`OXOBJECTID`);

ALTER TABLE oxgroups add WWDISPLAYPRODUCTSFOROTHER TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE oxmediaurls add WWUPLOADDATE DATETIME(3) NOT NULL;
ALTER TABLE oxgroups add WWNETTOMODE TINYINT(1) NOT NULL;

CREATE TABLE IF NOT EXISTS `oxdiscountaccessory` (
  `OXID` CHAR(32) COLLATE latin1_general_ci NOT NULL ,
  `OXQUANTITY` FLOAT NOT NULL ,
  `OXPRICE` FLOAT NOT NULL ,
  `OXCARTTYPE` INT(2) NOT NULL,
  `OXGROUPS` TEXT NOT NULL,
  `OXEXCLUDEDGROUPS` TEXT NOT NULL,
  `OXARTICLEID` CHAR(32) COLLATE latin1_general_ci NOT NULL ,
  `OXDISCOUNTID` CHAR(32) COLLATE latin1_general_ci NOT NULL ,
  PRIMARY KEY (`OXID`), INDEX (`OXARTICLEID`), INDEX (`OXDISCOUNTID`));

alter table oxmanufacturers add WWCOMPANY varchar(256) NOT NULL;
alter table oxmanufacturers add WWADDRESS varchar(256) NOT NULL;
alter table oxmanufacturers add WWEMAIL varchar(256) NOT NULL;
alter table oxmanufacturers add WWURL varchar(256) NOT NULL;
alter table oxmanufacturers add WWIMPORTERCOMPANY varchar(256) NOT NULL;
alter table oxmanufacturers add WWIMPORTERADDRESS varchar(256) NOT NULL;
alter table oxmanufacturers add WWIMPORTEREMAIL varchar(256) NOT NULL;
alter table oxmanufacturers add WWIMPORTERURL varchar(256) NOT NULL;
alter table oxmanufacturers add WWRESPONSIBLEPERSON varchar(256) NOT NULL;
alter table oxmanufacturers add WWRESPONSIBLEPERSONADDRESS varchar(256) NOT NULL;
alter table oxmanufacturers add WWRESPONSIBLEPERSONEMAIL varchar(256) NOT NULL;
alter table oxmanufacturers add WWRESPONSIBLEPERSONURL varchar(256) NOT NULL;
alter table oxmanufacturers add WWCUSTOMGPSRTEXTFORLONGDESCRIPTION text NOT NULL;